#!/usr/bin/env python3
"""
generate-readme.py

Walks the docs/ directory and compiles every Markdown file into a single
README.md at the repository root.

Directory-level README.md files are always placed first within their section,
followed by the remaining .md files sorted alphabetically.  Non-Markdown files
(e.g. YAML) are skipped.

Usage:
    python3 scripts/generate-readme.py [--docs-dir DOCS_DIR] [--output OUTPUT]

Defaults:
    --docs-dir  docs
    --output    README.md
"""

import argparse
import os
import sys


HEADER = """\
<!-- This file is auto-generated by scripts/generate-readme.py -->
<!-- Do not edit it directly – edit templates under templates/ and data under data/ instead -->

# Homelab Docs

"""


def _is_readme(filename: str) -> bool:
    """Return True when *filename* is a README.md (case-insensitive)."""
    stem, ext = os.path.splitext(filename)
    return stem.upper() == "README" and ext.lower() == ".md"


def collect_files(docs_dir: str) -> list[str]:
    """Return an ordered list of Markdown files under *docs_dir*.

    Rules:
    - Directories are visited in alphabetical order.
    - Within each directory, README.md comes first, then other .md files in
      alphabetical order.
    """
    result: list[str] = []
    for root, dirs, files in os.walk(docs_dir):
        dirs.sort()
        md_files = [f for f in files if f.lower().endswith(".md")]
        readme = [f for f in md_files if _is_readme(f)]
        others = sorted(f for f in md_files if not _is_readme(f))
        for fname in readme + others:
            result.append(os.path.join(root, fname))
    return result


def build_toc(files: list[str], docs_dir: str) -> str:
    """Build a simple Table of Contents from the collected file list."""
    lines = ["## Table of Contents", ""]
    for path in files:
        rel = os.path.relpath(path, docs_dir)
        # Derive a human-readable section name from the file path
        parts = rel.replace("\\", "/").split("/")
        if _is_readme(parts[-1]):
            label = " / ".join(p.replace("-", " ").title() for p in parts[:-1]) or "Overview"
        else:
            stem = os.path.splitext(parts[-1])[0].replace("-", " ").title()
            section = " / ".join(p.replace("-", " ").title() for p in parts[:-1])
            label = f"{section} / {stem}" if section else stem
        # GitHub anchor: lowercase, spaces → hyphens, strip special chars
        anchor = label.lower().replace(" / ", "--").replace(" ", "-")
        anchor = "".join(c for c in anchor if c.isalnum() or c == "-")
        lines.append(f"- [{label}](#{anchor})")
    lines.append("")
    return "\n".join(lines)


def section_title(path: str, docs_dir: str) -> str:
    """Return a Markdown heading to use as a section separator."""
    rel = os.path.relpath(path, docs_dir)
    parts = rel.replace("\\", "/").split("/")
    if _is_readme(parts[-1]):
        label = " / ".join(p.replace("-", " ").title() for p in parts[:-1]) or "Overview"
    else:
        stem = os.path.splitext(parts[-1])[0].replace("-", " ").title()
        section = " / ".join(p.replace("-", " ").title() for p in parts[:-1])
        label = f"{section} / {stem}" if section else stem
    return f"---\n\n## {label}\n\n*Source: `{rel}`*\n"


def generate(docs_dir: str, output: str) -> None:
    files = collect_files(docs_dir)
    if not files:
        print(f"No Markdown files found under '{docs_dir}'.", file=sys.stderr)
        sys.exit(1)

    parts = [HEADER, build_toc(files, docs_dir)]

    for path in files:
        parts.append(section_title(path, docs_dir))
        with open(path, encoding="utf-8") as fh:
            content = fh.read().rstrip("\n")
        parts.append(content + "\n")

    with open(output, "w", encoding="utf-8") as fh:
        fh.write("\n".join(parts) + "\n")

    print(f"Generated '{output}' from {len(files)} file(s).")


def main() -> None:
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--docs-dir",
        default=os.path.join(repo_root, "docs"),
        help="Root directory containing documentation (default: <repo>/docs)",
    )
    parser.add_argument(
        "--output",
        default=os.path.join(repo_root, "README.md"),
        help="Output file path (default: <repo>/README.md)",
    )
    args = parser.parse_args()
    generate(args.docs_dir, args.output)


if __name__ == "__main__":
    main()
