#!/usr/bin/env python3
"""
generate-docs.py

Loads YAML data files from data/network/ and renders Jinja2 templates from
templates/network/ into docs/network/.

The YAML files are the source of truth.  Templates define the prose and
structure of each document.  Running this script regenerates the docs to
match the current YAML data.

Usage:
    python3 scripts/generate-docs.py [--data-dir DATA_DIR]
                                     [--templates-dir TEMPLATES_DIR]
                                     [--output-dir OUTPUT_DIR]

Defaults:
    --data-dir       data/network
    --templates-dir  templates/network
    --output-dir     docs/network
"""

import argparse
import os
import sys

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined


def load_yaml_dir(data_dir: str) -> dict:
    """Load and merge all YAML files from *data_dir* into a single dict."""
    merged: dict = {}
    if not os.path.isdir(data_dir):
        print(f"Data directory not found: '{data_dir}'", file=sys.stderr)
        sys.exit(1)
    for fname in sorted(os.listdir(data_dir)):
        if not fname.lower().endswith((".yaml", ".yml")):
            continue
        fpath = os.path.join(data_dir, fname)
        with open(fpath, encoding="utf-8") as fh:
            data = yaml.safe_load(fh)
        if not isinstance(data, dict):
            print(f"Warning: '{fpath}' did not parse as a mapping; skipping.", file=sys.stderr)
            continue
        merged.update(data)
    return merged


def render_templates(data: dict, templates_dir: str, output_dir: str) -> None:
    """Render every *.j2 template in *templates_dir* into *output_dir*."""
    if not os.path.isdir(templates_dir):
        print(f"Templates directory not found: '{templates_dir}'", file=sys.stderr)
        sys.exit(1)

    os.makedirs(output_dir, exist_ok=True)

    env = Environment(
        loader=FileSystemLoader(templates_dir),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )

    # Expose dict.get as a Jinja2 filter so templates can call obj.get(key)
    env.filters["attr"] = lambda obj, name: getattr(obj, name, None) if not isinstance(obj, dict) else obj.get(name)

    templates = sorted(
        t for t in env.list_templates() if t.endswith(".j2")
    )
    if not templates:
        print(f"No .j2 templates found in '{templates_dir}'.", file=sys.stderr)
        sys.exit(1)

    generated = []
    for tname in templates:
        # Strip the .j2 suffix to get the output filename
        out_fname = tname[:-3]
        out_path = os.path.join(output_dir, out_fname)

        template = env.get_template(tname)
        rendered = template.render(**data)

        # Prepend auto-generated notice
        notice = (
            f"<!-- Generated by scripts/generate-docs.py from templates/{tname} -->\n"
            f"<!-- Edit the template or data files in data/, not this file directly -->\n\n"
        )
        rendered = notice + rendered

        # Ensure the file ends with exactly one newline
        rendered = rendered.rstrip("\n") + "\n"

        with open(out_path, "w", encoding="utf-8") as fh:
            fh.write(rendered)

        generated.append(out_path)
        print(f"  {tname} -> {out_path}")

    print(f"Generated {len(generated)} file(s) from templates.")


def main() -> None:
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--data-dir",
        default=os.path.join(repo_root, "data", "network"),
        help="Directory containing YAML data files (default: <repo>/data/network)",
    )
    parser.add_argument(
        "--templates-dir",
        default=os.path.join(repo_root, "templates", "network"),
        help="Directory containing Jinja2 templates (default: <repo>/templates/network)",
    )
    parser.add_argument(
        "--output-dir",
        default=os.path.join(repo_root, "docs", "network"),
        help="Directory to write generated docs (default: <repo>/docs/network)",
    )
    args = parser.parse_args()

    print(f"Loading data from '{args.data_dir}'...")
    data = load_yaml_dir(args.data_dir)

    print(f"Rendering templates from '{args.templates_dir}' into '{args.output_dir}'...")
    render_templates(data, args.templates_dir, args.output_dir)


if __name__ == "__main__":
    main()
